### ISSUE TITLE
I want to know how to develop this repo

### ISSUE THREAD

**Issue by Ctum** [daruk-framework/daruk#11]
**Describe the bug**
i want to kow how to develop this framework, by the way, there is only build script and i don't konw it works

**Comment by Ctum** [comment]
by the way, build/test/tslint scripts can't be executed in win10

**Comment by galaa2011** [comment]
@Ctum 你直接说中文吧

**Comment by xiaojue** [comment]
@Ctum you can upload the win10 error screenshots~ I just know is what circumstance。

**Comment by Ctum** [comment]
build/ rm can only work in bash
test  TS_NODE_FILES=true  --> set TS_NODE_FILES=true it will work
tslint it works but show
![捕获](https://user-images.githubusercontent.com/31543505/56881325-a3f4a700-6a92-11e9-8385-e587d27f701d.JPG)
**What I really want to know is how to develop, like front-end, it will change view when i change something in source code, but how i konw it works when i change something in it**

**Comment by xiaojue** [comment]
https://github.com/daruk-framework/daruk/pull/13

Fix the tslint error and rm in windows platform problem, and add a develop for contribute documents: https://github.com/daruk-framework/daruk/blob/master/docs/how-to-contribute.md
