### ISSUE TITLE
你好，我在win10下安装daruk不成功

### ISSUE THREAD

**Issue by vincentCheng** [daruk-framework/daruk#15]
提示：
'yarn' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

这个必须要用yarn吗？

**Comment by Youjingyu** [comment]
你没安装 yarn 吧，不一定要用 yarn，用 npm、cnpm 也可以，如下命令都可以：
```bash
npm install daruk
# 或者
cnpm install daruk
# 或者
yarn add daruk
```

**Comment by xiaojue** [comment]
建议使用yarn，yarn比cnpm npm 都要快速和高效。

https://yarnpkg.com/zh-Hant/

当然使用cnpm和npm也可以。安装方法见楼上，先关闭了。

**Comment by xiaojue** [comment]
npm install yarn -g

😄

**Comment by vincentCheng** [comment]
@xiaojiu
感谢回复。
yarn安装比较困难，我还是搞定了。

**Comment by vincentCheng** [comment]
这一步还是建议增加对cnpm npm的支持。
主要是对我这种小白，如果安装不了小白们就流失掉了。

**Comment by xiaojue** [comment]
嗯 我增加一个 cnpm和npm的选项明天
