### ISSUE TITLE
Router version（controller version）

### ISSUE THREAD

**Issue by Chersquwn** [daruk-framework/daruk#22]
Is it possible to add a uniform public version to the router, or use V1ContactList directly?

```ts
// src/controllers/contact/list.ts
import { BaseController, get, Context } from "daruk";

export default class V1ContactList extends BaseController {
  @get("/")
  public async getContactList(ctx: Context, next: Function) {
    ctx.body = "contact list";
    return next();
  }
}
```

Is there any other way to achieve it? such as

```ts
// src/controllers/contact/list.ts
import { BaseController, get, Context, version } from "daruk";

@version('/v1')
export default class ContactList extends BaseController {
  @get("/")
  public async getContactList(ctx: Context, next: Function) {
    ctx.body = "contact list";
    return next();
  }
}
```

**Comment by xiaojue** [comment]
it like a prefix controller decorator.

```js
// src/controllers/contact/list.ts
import { BaseController, get, Context, version } from "daruk";

@prefixPath('/v1')
export default class ContactList extends BaseController {
  @get("/")
  public async getContactList(ctx: Context, next: Function) {
    ctx.body = "contact list";
    return next();
  }
}
```

the router path use with @prefixPath decorator will be `/v1/contact/list`,  it's should be better ?

**Comment by Himself65** [comment]
someone could change this line to
`this._prefix + method` and add a new decorator named "prefix" which add _prefix to target class

https://github.com/daruk-framework/daruk/blob/ef2e002d2feb48575f02587e36fb67720b49260a/src/decorators/http_methods.ts#L68

**Comment by Himself65** [comment]
someone could change this line to
`this._prefix + method` and add a new decorator named "prefix" which add _prefix to target class

https://github.com/daruk-framework/daruk/blob/ef2e002d2feb48575f02587e36fb67720b49260a/src/decorators/http_methods.ts#L68

**Comment by xiaojue** [comment]
https://github.com/daruk-framework/daruk/commit/7a48705c7fa5768030c7902980f5748aa62ed472

@Chersquwn  next version will be available
