### ISSUE TITLE
[Feature Request] http_method handle with RegExp

### ISSUE THREAD

**Issue by Himself65** [daruk-framework/daruk#35]
example:

```ts
@get(/\/(foo|goo)/)
async foo(ctx: Daruk.Context) {
  ctx.body = '';
}
```

**Comment by Himself65** [comment]
如果加入该特性会和该部分冲突

https://github.com/daruk-framework/daruk/blob/5e80b4cbe935c92b9a092116354b7e61e4fe750a/src/core/daruk_init_module.ts#L185-L193

**Comment by xiaojue** [comment]
@Himself65 koa-router是支持字符串通配符的，所以之前直接传入字符串就可以，如果要加入正则，这里需要做逻辑分支处理，这个地方应该也是引起windows报错的地方，建议windows的router我们下午搞定了，再加这个特性。

**Comment by xiaojue** [comment]
https://github.com/pillarjs/path-to-regexp#custom-matching-parameters

```ts
@get('/(foo|goo)')
async foo(ctx: Daruk.Context) {
  ctx.body = '';
}
```
查阅了一下，koa-router是基于path-to-regexp这个库，所以是可以通过字符串通配方式进行正则表达式的替换，参考我发的例子，可以实现，所以这个feature可以不加。koa-router也是不支持regexp参数。
