### ISSUE TITLE
remove vscode settings

### ISSUE THREAD

**Issue by zhmushan** [daruk-framework/daruk#41]
I don't know if the vscode setting has other uses. At least we should remove the icon config because I have not installed the extension.

**Comment by xiaojue** [comment]
i think the launch setting could be saved，the project need debug launch。

**Comment by xiaojue** [comment]
https://github.com/daruk-framework/daruk/blob/developer/.vscode/settings.json

i will remove it with .gitignore tomorrow.

**Comment by xiaojue** [comment]
https://github.com/daruk-framework/daruk/commit/926dbeef0c01d9b829862469d5b0af6e3b667536
