### ISSUE TITLE
add contributors

### ISSUE THREAD

**Issue by xiaojue** [daruk-framework/daruk#5]
@all-contributors please add @xiaojue for design

**Comment by xiaojue** [comment]
@all-contributors please add @xiaojue  for design and code

**Comment by xiaojue** [comment]
@all-contributors please add @zgayjjf for code

**Comment by Himself65** [comment]
@all-contributors please add @yiliang114 for doc

**Comment by xiaojue** [comment]
@all-contributors please add @alex1504 for tests and code

**Comment by xiaojue** [comment]
https://github.com/all-contributors please add @xiaoqiang1999  for tests and code

**Comment by xiaojue** [comment]
@all-contributors please add @xiaoqiang1999 for tests and code
