### ISSUE TITLE
[Discussion] should configurable by user on Daruk.[module] ?

### ISSUE THREAD

**Issue by Himself65** [daruk-framework/daruk#57]
as we all know, React.js have `setState` to change states. and in our Daruk, how about when user code `Daruk.itils.function1 = () => {}` and function1 have assigned

**Comment by xiaojue** [comment]
If user want extends Daruk by self，maybe use class inherits is best way.

`class mydaruk extends Daruk {}`

**Comment by Himself65** [comment]
emm, no, my meaning is that if user change utils function which loaded from `utils` folder, should we log warning or ban this behavior

**Comment by Himself65** [comment]
and the implement of this discussion #58

**Comment by xiaojue** [comment]
Well done！tks @Himself65
